//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WatchIt.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    [Bind(Exclude = "Id")]   
    public partial class User
    {

        public int Id { get; set; }
        [Required(ErrorMessage = "An UserName is required")]
        public string UserName { get; set; }
        [Required(ErrorMessage = "An Password is required")]
        public string Password { get; set; }
    }
}
